---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readr)
library(sf)
library(tmap)
library(tidyverse)
library(dplyr)
library(here)
library(janitor)
library(lubridate)
library(tidycensus)
library(ggmap)
```


```{r}
url <- "https://s3.amazonaws.com/capitalbikeshare-data/202109-capitalbikeshare-tripdata.zip"

download.file(url, destfile = "../data/raw/capitalshare.csv.zip", mode = "wb")
unzip("../data/raw/capitalshare.csv.zip", exdir = "../data/raw")
```

```{r}
capitalshare <- read_csv("../data/raw/202109-capitalbikeshare-tripdata.csv", show_col_types = FALSE)

stations <- capitalshare %>%
  select(start_station_name, start_lat, start_lng) %>%
  distinct(start_station_name, .keep_all=TRUE)

neighborhoods <- sf::read_sf("../data/raw/dc-neighborhoods")
#ggplot(neighborhoods)+geom_sf()
#plot(neighborhoods)
```

Read in geojson file from the dc-health-planning-neighborhoods open dc page.

```{r}
neigh = st_read(here("data", "raw", "dc_neigh.geojson")) %>% clean_names()
```

```{r}
df_c=readxl::read_excel(here("data","raw","neigh_cases.xlsx"), col_types = c("date", "text", "numeric")) %>% clean_names()
```

```{r}
df_cases=df_c %>%
  #filter(as_date(date) == "2021-11-17") %>% 
  separate(neighborhood,into=c("code","name"),sep = ":") %>%
  mutate(code=case_when(
    code=="N35" ~"N0",
    TRUE ~ code
  ))
```


```{r}
neigh2=left_join(neigh,df_cases,by=c("code"))
```

Determine the number of riders that started on each day per station.

```{r}
riders_day <- capitalshare %>%
  #select(started_at, ended_at, start_station_name, end_station_name, start_lat, start_lng, end_lat, end_lng) %>%
  mutate(start_date = date(started_at), end_date = date(ended_at)) %>%
  group_by(start_date, start_station_name) %>%
  summarise(riders = n()) %>%
  drop_na()
```

Add coordinates of stations by joining.

```{r}
riders_day_loc <- left_join(riders_day, stations, by = "start_station_name")
```

Change to sf format.

```{r}
riders_sf <- st_as_sf(riders_day_loc, coords = c("start_lng", "start_lat"), crs = 4326)
```

```{r}
df <- st_intersects(neigh2, riders_sf)
int <- df[[1]]
```





might use https://www.jessesadler.com/post/geocoding-with-r/

```{r}
df_trans <- df_cases %>% st_transform(4326)
```













