---
title: "R Notebook"
output: html_notebook
---

https://opendata.dc.gov/datasets/dc-health-planning-neighborhoods/explore?location=38.890614%2C-77.022347%2C12.61

```{r}
library(readr)
library(sf)
library(tmap)
library(tidyverse)
library(dplyr)
library(here)
library(janitor)
library(lubridate)
library(tidycensus)
```


```{r}
url <- "https://s3.amazonaws.com/capitalbikeshare-data/202109-capitalbikeshare-tripdata.zip"

download.file(url, destfile = "../data/raw/capitalshare.csv.zip", mode = "wb")
unzip("../data/raw/capitalshare.csv.zip", exdir = "../data/raw")

capitalshare <- read_csv("../data/raw/202109-capitalbikeshare-tripdata.csv", show_col_types = FALSE)

stations <- capitalshare %>%
  select(start_station_name, start_lat, start_lng) %>%
  distinct(start_station_name, .keep_all=TRUE)

neighborhoods <- sf::read_sf("../data/raw/dc-neighborhoods")
ggplot(neighborhoods)+geom_sf()
plot(neighborhoods)
```

Read in geojson file from the dc-health-planning-neighborhoods open dc page.

```{r}
neigh = st_read(here("data", "raw", "dc_neigh.geojson")) %>% clean_names()
```

```{r}
df_c=readxl::read_excel(here("data","raw","neigh_cases.xlsx"),
                            col_types = c("date", "text", "numeric")) %>% 
  clean_names() 
df_cases=df_c %>%
  filter(as_date(date) == "2021-11-17") %>% 
  separate(neighborhood,into=c("code","name"),sep = ":") %>%
  mutate(code=case_when(
    code=="N35" ~"N0",
    TRUE ~ code
  ))
```

Joining

```{r}
neigh2=left_join(neigh,df_cases,by=c("code")) 
tmap_mode("view")
tm_shape(neigh2) +tm_polygons("total_positives",alpha=.5)
```

```{r}
census_api_key("e811d2bef60d1bcf657f8c0222687e80e03335da")
#what variables
v20 = load_variables(2018,"acs5")
# median_family_income="	B06011_001" 
# all "B00001_001"	
#black "B02009_001"
```


Get some data:

```{r}
df_cencus=get_acs(geography = "tract",
                  variables=c("median_inc"="B06011_001",
                              "pop"="B01001_001",
                              "pop_black"="B02009_001"),
                  state="DC",geometry=TRUE,year=2018) 
```

```{r}
class(df_cencus)
plot(df_cencus)
```
It's in long format.  Let's make it wide.
```{r}
df_cens=df_cencus %>% select(-moe) %>% spread(variable,estimate) 
tm_shape(df_cens) +tm_polygons("median_inc",alpha=.5)
```


```{r}
  tm_shape(neigh2) +tm_borders(col="blue",lwd=5,alpha=.2)+
  tm_shape(df_cens) +tm_borders(col="red",lwd=1,alpha=.3)
```



```{r}
df_j=st_join(df_cens,neigh2,prepared=FALSE)
```

```{r}
df_cens_adj=df_cens %>% st_transform(4326)
```

```{r}
df_j=st_join(df_cens_adj,neigh2,largest=TRUE)
```
Other order?:

```{r}
df_j_rev = st_join(neigh2,df_cens_adj,largest=TRUE)
```

Since we want the geometry for the NEIGHBORHOODS, we need a different work a little harder:

```{r}
df1=df_j %>% select(median_inc,pop,pop_black,objectid) %>%
  group_by(objectid) %>%
  summarise(pop_n=sum(pop),
            pop_black_n=sum(pop_black), 
            adj_median_income=sum(pop*median_inc)/pop_n) 
plot(df1)
```

```{r}
df2=left_join(neigh2,df1)
df2=left_join(neigh2,df1 %>% st_set_geometry(NULL))
```

```{r}
df2=df2 %>% mutate(black_perc=pop_black_n/pop_n, covid_rate=total_positives/pop_n)
tm_shape(df2)+tm_polygons(c("adj_median_income","covid_rate","black_perc"))
```



```{r}
df2 %>% filter(objectid!=35) %>% tm_shape()+tm_polygons(c("adj_median_income","covid_rate","black_perc"),alpha=.4)
```



