---
title: "Bike Analysis"
author: "Shreejit Poudyal"
date: "11/17/2021"
output: html_document
---

### Loading Packages

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(readr)
library(lubridate)
library(janitor)
library(here)
```

### Data

```{r, include = FALSE}
data <- read_csv("https://raw.githubusercontent.com/jskufca/DS241_bikes_2021/shreejit/crime_data/crime_processed/final.csv")
```

### Prepping Data

```{r, include = FALSE}
main <- data %>%
  select(CCN:OBJECTID) %>%
  rename(complaint_num = CCN) %>%
  rename(report_date = REPORT_DAT) %>%
  rename(shift = SHIFT) %>%
  rename(method = METHOD) %>%
  rename(offense = OFFENSE) %>%
  rename(block = BLOCK) %>%
  rename(x_block = XBLOCK) %>%
  rename(y_block = YBLOCK) %>%
  rename(ward = WARD) %>%
  rename(anc = ANC) %>% # Advisory Neighborhood Commission
  rename(district = DISTRICT) %>%
  rename(psa = PSA) %>% # Police Service Area
  rename(nbhd_cluster = NEIGHBORHOOD_CLUSTER) %>%
  rename(block_grp = BLOCK_GROUP) %>%
  rename(census_tract = CENSUS_TRACT) %>%
  rename(precinct = VOTING_PRECINCT) %>%
  rename(latitude = LATITUDE) %>%
  rename(longitude = LONGITUDE) %>%
  rename(bid = BID) %>% # Business Improvement District
  rename(start = START_DATE) %>%
  rename(end = END_DATE) %>%
  rename(object_id = OBJECTID) %>%
  mutate(report_date = substr(report_date, 1, nchar(report_date)-3),
         report_date = as_datetime(report_date),
         start = substr(start, 1, nchar(start)-3),
         start = as_datetime(start),
         end = substr(end, 1, nchar(end)-3),
         end = as_datetime(end),
         nbhd_cluster = as.numeric(substring(nbhd_cluster, 9)),
         precinct = as.numeric(substring(precinct, 10)),
         block_grp = as.numeric(substring(block_grp, 8)),
         census_tract = as.numeric(census_tract),
         shift=str_to_sentence(shift),
         method=str_to_sentence(method),
         offense=str_to_sentence(offense),
         bid=str_to_title(bid))
```

### Making Visualizations form the Data

#### Time of the day

```{r}
ggplot(main, aes(fct_infreq(shift), fill=shift)) +
  geom_bar() +
  labs(
    x="Time of Day",
    y="Number of Crimes Reported")+
  theme(legend.position = "none")
```

#### Crimes by Hour

```{r}
ggplot(main, aes(hour(report_date)), fill=shift) +
  geom_bar() +
  labs(
    x="Hour of the Day",
    y="Number of Crimes Reported",
    title="Crimes by Hour")+
  theme(legend.position = "none")
```

#### Method

```{r}
ggplot(main, aes(x=fct_infreq(method), fill=method)) +
  geom_bar() +
  labs(
    x="Weapon of use",
    y="Number of Crimes Reported",
    fill="Method",
    title="Method of Crime") +
  scale_y_continuous(labels = scales::comma)+
  theme(legend.position = "none")
```

#### Offense

```{r}
ggplot(main, aes(x=fct_infreq(offense), fill=offense)) +
  geom_bar(stat='count') +
  #coord_cartesian(ylim=c(0,100)) + # Number of Arson crimes   is very small (<50)
  labs(
    x="Crime",
    y="Number of Crimes Reported",
    fill="Offense",
    title="Criminal Offense") +
    theme(axis.text.x = element_text(angle = 30, hjust=1)) +
    theme(legend.position = "none")
```

#### Total Crimes since 2017 (by month)

```{r}
ggplot(main, aes(factor(month(report_date, label=TRUE)))) +
  geom_bar() +
  labs(
    x="Year",
    y="Number of Crimes Reported") +
    theme(legend.position = "none")
```

#### Yearwise Number of crimes

```{r}
ggplot(main, aes(factor(year(report_date)))) +
  geom_bar() +
  labs(
    x="Year",
    y="Number of Crimes Reported") +
    theme(legend.position = "none")
```
#### Did COVID impact crimes in December 2019 ?

```{r}
data_2019 <- main %>%
  filter(year(report_date)==2019)

ggplot(data_2019, aes(factor(month(report_date, label=TRUE)))) +
  geom_bar() +
  labs(
    x="Year",
    y="Number of Crimes Reported",
    title="Number of Crimes Reported per month in 2019") +
    theme(legend.position = "none")
```
#### How about 2020 ?

```{r}
data_2020 <- main %>%
  filter(year(report_date)==2020)

ggplot(data_2020, aes(factor(month(report_date, label=TRUE)))) +
  geom_bar() +
  labs(
    x="Year",
    y="Number of Crimes Reported",
    title="Number of Crimes Reported per month in 2020") +
    theme(legend.position = "none")
```

#### Data for 2021

```{r}
data_2021 <- main %>%
  filter(year(report_date)==2021)

ggplot(data_2021, aes(factor(month(report_date, label=TRUE)))) +
  geom_bar() +
  labs(
    x="Year",
    y="Number of Crimes Reported",
    title="Number of Crimes Reported per month in 2020") +
    theme(legend.position = "none")
```     