<<<<<<< HEAD:jacksons_experiments.Rmd
---
title: "jacksons_experiments"
author: "Jackson"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(lubridate)
library(readr)
library(sf)
library(tmap)
```
# Importing the data from csv file
```{r}
data <- read.csv("bikeshare_data.csv")
# finding all unique bikeshare stations and a corresponding latitude and longitude for each station
stations <- data %>% select(start_station_name, start_lat, start_lng) %>% distinct(start_station_name, .keep_all=TRUE)
```

#__________________________________________________________________

Importing sf file as sf object
```{r}
neighborhoods <- sf::read_sf("dc_map_data")
```

```{r}
ggplot(neighborhoods)+geom_sf()
```

```{r}
plot(neighborhoods)
```


```{r}
map_dc <- tm_shape(neighborhoods)
```

=======
---
title: "jacksons_experiments"
author: "Jackson"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(lubridate)
```

>>>>>>> b1a5c0e67599a28ec3df216d22c75b2dd093d78b:notebooks/jacksons_experiments.Rmd
